/**
 * Derives the UI-facing message list (with a per-turn "how was this
 * resolved" marker) from a DialogueState's plain {role, content} history.
 *
 * DialogueTurn (lib/dialogue/types.ts) deliberately has no `resolvedBy`
 * field -- that type is shared with the AIML/dialogue system and out of
 * scope to change here. Instead, the resolution marker for each assistant
 * turn is carried in a small parallel structure keyed by that turn's index
 * in `history`, owned by the chat UI layer (see components/chat/useChatSession.ts).
 * This is intentionally NOT persisted alongside dialogueState: it's a
 * same-session UI affordance, not part of the durable conversation record.
 */

import type { DialogueTurn } from "../dialogue/types";

// Resolved deterministically by the AIML-style pattern matcher (cheap,
// synchronous, no model weights involved) vs. generated by the ternary GPT
// transformer in the Web Worker (the fallback path, used only when no
// unambiguous deterministic match exists).
export type ResolvedBy = "deterministic" | "generated";

export interface ChatMessage {
  id: string;
  role: "user" | "assistant";
  content: string;
  resolvedBy?: ResolvedBy;
}

/** Maps a turn's index in `history` to how that (assistant) turn was
 * resolved. Only assistant-turn indices are ever populated. */
export type ResolvedByIndex = Record<number, ResolvedBy>;

/**
 * Builds the rendered message list for a conversation. `idPrefix` (e.g. the
 * conversation id) keeps React keys unique when messages from different
 * conversations are ever rendered in the same tree at once.
 */
export function deriveMessages(
  history: DialogueTurn[],
  resolvedByIndex: ResolvedByIndex,
  idPrefix: string = "m",
): ChatMessage[] {
  return history.map((turn, index) => ({
    id: `${idPrefix}-${index}`,
    role: turn.role,
    content: turn.content,
    resolvedBy: turn.role === "assistant" ? resolvedByIndex[index] : undefined,
  }));
}
