import Link from "next/link";
import styles from "./page.module.css";
import {
  ARCHITECTURE,
  EMBEDDING_PARAMS,
  FP16_BASELINE_SIZE_MB,
  MEASURED_COMPRESSION_RATIO,
  MODEL_NAME,
  MODEL_SUBTITLE,
  PACKED_FILE_SIZE_MB,
  TERNARY_PARAMS,
  TOTAL_PARAMS,
  TRAINING_BUDGET_TOKENS,
  formatParams,
} from "../lib/modelInfo";

export default function Home() {
  const fp16Pct = 100;
  const ternaryPct = (PACKED_FILE_SIZE_MB / FP16_BASELINE_SIZE_MB) * 100;

  return (
    <div>
      <section className={styles.hero}>
        <div className={styles.eyebrow}>{MODEL_SUBTITLE}</div>
        <h1 className={styles.title}>{MODEL_NAME} runs a real language model entirely in your browser.</h1>
        <p className={styles.subtitle}>
          {MODEL_NAME} is a {formatParams(TOTAL_PARAMS)}-parameter, ternary-weight (“BitNet b1.58”-style)
          decoder-only transformer, compiled to WebAssembly and executed 100% client-side &mdash; no
          server, no API key, no data leaving your device.
        </p>
        <div className={styles.ctaRow}>
          <Link href="/demo" className="button">
            Try the live demo
          </Link>
          <Link href="/about" className="buttonSecondary button">
            Read the recipe
          </Link>
        </div>
      </section>

      <section className={styles.section}>
        <div className="callout">
          <strong>Runs 100% in your browser.</strong> Once the model file is downloaded, every token is
          generated by a WebAssembly module executing on your own CPU. There is no inference server and
          no network call made to generate text &mdash; the demo works offline after the first load.
        </div>
      </section>

      <section className={styles.section}>
        <div className="callout warning">
          <strong>This specific model file is an untrained placeholder.</strong> The weights shipped in
          this demo are randomly initialized &mdash; they exercise the real architecture and the real
          ternary packing format, but the model has not yet been through its Chinchilla-optimal training
          run. That run happens on separate hardware, outside this repo’s CI, and hasn’t completed yet.
          Until then, expect the demo to produce fluent-looking but meaningless token sequences, not
          coherent answers.
        </div>
      </section>

      <section className={styles.section}>
        <h2>Architecture</h2>
        <p>
          {MODEL_NAME} is a {ARCHITECTURE.nLayers}-layer, {ARCHITECTURE.dModel}-dim,{" "}
          {ARCHITECTURE.nHeads}-head decoder-only transformer. Every attention and feed-forward
          projection is a <code>BitLinear</code> layer: weights are quantized at train time to{" "}
          {ARCHITECTURE.weightScheme}, so each weight costs roughly 1.58 bits instead of 16.
        </p>
        <div className={styles.specGrid}>
          <div className={styles.specCard}>
            <div className={styles.specValue}>{formatParams(TOTAL_PARAMS)}</div>
            <div className={styles.specLabel}>total parameters</div>
          </div>
          <div className={styles.specCard}>
            <div className={styles.specValue}>{ARCHITECTURE.nLayers}</div>
            <div className={styles.specLabel}>transformer layers</div>
          </div>
          <div className={styles.specCard}>
            <div className={styles.specValue}>{ARCHITECTURE.dModel}</div>
            <div className={styles.specLabel}>model dimension</div>
          </div>
          <div className={styles.specCard}>
            <div className={styles.specValue}>{ARCHITECTURE.nHeads}</div>
            <div className={styles.specLabel}>attention heads</div>
          </div>
          <div className={styles.specCard}>
            <div className={styles.specValue}>{ARCHITECTURE.contextLen}</div>
            <div className={styles.specLabel}>context length (tokens)</div>
          </div>
          <div className={styles.specCard}>
            <div className={styles.specValue}>{ARCHITECTURE.vocabSize.toLocaleString()}</div>
            <div className={styles.specLabel}>vocab size</div>
          </div>
        </div>
        <p style={{ marginTop: 20 }}>
          Training budget target: <strong>{TRAINING_BUDGET_TOKENS}</strong>, sized to this model’s
          parameter count per Chinchilla scaling-law guidance rather than an arbitrarily large corpus.
        </p>
      </section>

      <section className={styles.section}>
        <h2>Ternary vs. fp16: the measured size, not the assumed one</h2>
        <p>
          It’s tempting to assume ternary weights give you a flat 16x/1.58 &asymp; 10x, or at least a
          ‘5-8x’ reduction over fp16. The number that actually ships in{" "}
          <code>benny-placeholder.bnai</code> is smaller than that, and it’s worth explaining why.
        </p>
        <div className={styles.compareBars}>
          <div className={styles.compareRow}>
            <span>fp16 baseline</span>
            <div className={styles.barTrack}>
              <div className={styles.barFill} style={{ width: `${fp16Pct}%`, background: "var(--fg-muted)" }} />
            </div>
            <span className="mono">{FP16_BASELINE_SIZE_MB.toFixed(1)} MB</span>
          </div>
          <div className={styles.compareRow}>
            <span>{MODEL_NAME} packed (.bnai)</span>
            <div className={styles.barTrack}>
              <div className={styles.barFill} style={{ width: `${ternaryPct}%` }} />
            </div>
            <span className="mono">{PACKED_FILE_SIZE_MB.toFixed(2)} MB</span>
          </div>
        </div>
        <p className={styles.ratioNote}>
          Measured compression ratio: <strong>{MEASURED_COMPRESSION_RATIO.toFixed(1)}x</strong> smaller
          than the fp16-equivalent baseline &mdash; not the 5-8x you might assume from ‘ternary weights.’
        </p>
        <p className={styles.paramSplit}>
          Why: of the {formatParams(TOTAL_PARAMS)} total parameters, the tied input/output embedding
          table (&asymp;{formatParams(EMBEDDING_PARAMS)} params) is kept at fp16 to protect quality on
          such a small model, and only the attention/FFN projections (&asymp;
          {formatParams(TERNARY_PARAMS)} params) are actually ternary-packed. The embedding table alone
          would dominate a naively ‘everything is ternary’ estimate.
        </p>
      </section>

      <section className={styles.section}>
        <h2>Packed model file</h2>
        <p>
          The file the browser downloads for the demo is <code>benny-placeholder.bnai</code>, currently{" "}
          <strong>{PACKED_FILE_SIZE_MB.toFixed(2)} MB</strong> on disk, plus a small (~16 KB) tokenizer
          JSON. It’s cached with the browser Cache API after the first download, so repeat visits don’t
          re-fetch it.
        </p>
        <div className={styles.ctaRow}>
          <Link href="/demo" className="button">
            Try the live demo
          </Link>
        </div>
      </section>
    </div>
  );
}
